[tool.poetry]
name = "gpt-engineer"
version = "0.0.1"
description = "Specify what you want it to build, the AI asks for clarification, and then builds it."
authors = ["Anton Osika <anton.osika@gmail.com>"]
readme = "README.md"
packages = [{ include = "gpt_engineer" }]

[tool.poetry.dependencies]
python = "^3.10"
openai = "^0.27.8"
typer = "^0.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
